version: '3.8'

services:
  sse-server:
    build: .
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DOTNET_SYSTEM_NET_SOCKETS_INLINE_COMPLETIONS=1
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2'
    ports:
      - "8080:8080"
    networks:
      - sse-net
    sysctls:
      - net.core.somaxconn=65535
      - net.ipv4.tcp_max_syn_backlog=65535
      - net.ipv4.ip_local_port_range=1024 65535

  load-tester:
    image: codesenberg/bombardier:latest
    depends_on:
      - sse-server
    command: ["-c", "50000", "-n", "1000000", "-m", "GET", "http://sse-server:8080/sse"]
    deploy:
      resources:
        limits:
          memory: 2G
    networks:
      - sse-net

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - sse-net

  monitoring:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - sse-net

networks:
  sse-net:
    driver: bridge

volumes:
  prometheus-data:
