version: '3.8'

services:
  sse-server:
    build: .
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DOTNET_SYSTEM_NET_SOCKETS_INLINE_COMPLETIONS=1
    ports:
      - "8080:8080"
    sysctls:
      - net.core.somaxconn=65535
      - net.ipv4.tcp_max_syn_backlog=65535
      - net.ipv4.ip_local_port_range=1024 65535
    ulimits:
      nofile:
        soft: 100000
        hard: 100000

  load-tester:
    image: codesenberg/bombardier:latest
    depends_on:
      - sse-server
    command: ["-c", "50000", "-n", "1000000", "-m", "GET", "http://sse-server:8080/sse"]
    sysctls:
      - net.ipv4.ip_local_port_range=1024 65535
    ulimits:
      nofile:
        soft: 100000
        hard: 100000
    privileged: true  # Required for high connection count
    network_mode: "host"  # Bypass Docker networking limitations

networks:
  default:
    driver: bridge
    name: sse-network
