global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'sse-server'
    static_configs:
      - targets: ['sse-server:8080']
        
  - job_name: 'node'
    static_configs:
      - targets: ['sse-server:9100']
